---
provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags

suites:
  - name: default
    run_list:
      - recipe[python-webapp-test::default]
