name 'python-webapp'
maintainer 'OSU Open Source Lab'
maintainer_email 'support@osuosl.org'
license 'Apache v2'
description 'Deploy python webapps'
long_description 'Deploys OSL webapps like GWM, ORVSD, or the Seagrant twins.'
version '0.1.0'

depends 'git'
depends 'python'
