name 'python-webapp'
maintainer 'Oregon State University'
maintainer_email 'chef@osuosl.org'
license 'Apache v2'
description 'Deploy python webapps'
long_description 'Deploys OSL webapps like GWM, ORVSD, or the Seagrant twins.'
version '0.1.1'

depends 'git'
depends 'gunicorn'
depends 'python'
depends 'supervisor'
